import React, { useState } from 'react';
import ApiRouteList from '../components/ApiRouteList';

const initialRoutes = [
  { id: 1, path: '/api/v1/superadmin/businesses', method: 'GET', description: 'Retrieve lists of onboarded business storefront tenants.', rateLimit: '100 req/min', scope: 'superadmin:read' },
  { id: 2, path: '/api/v1/superadmin/businesses', method: 'POST', description: 'Onboard a new business account credential.', rateLimit: '30 req/min', scope: 'superadmin:write' },
  { id: 3, path: '/api/v1/superadmin/billing/invoices', method: 'GET', description: 'Query payment invoices generated by sub-tenants.', rateLimit: '60 req/min', scope: 'billing:read' },
  { id: 4, path: '/api/v1/superadmin/system/status', method: 'GET', description: 'Check VM engine health thresholds.', rateLimit: '300 req/min', scope: 'monitoring:read' }
];

export default function DeveloperApis() {
  const [routes] = useState(initialRoutes);

  const handleTest = (path) => {
    alert(`Triggering test HTTP request to: ${path}`);
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ marginBottom: '20px', borderBottom: '1px solid #f3f4f6', paddingBottom: '14px' }}>
        <h2 style={{ margin: 0, fontSize: '18px', fontWeight: 700, color: '#1f2937' }}>Platform API Routes</h2>
        <p style={{ margin: '4px 0 0', fontSize: '12.5px', color: '#6b7280' }}>Review available super-administrator endpoints, access permissions, and rate throttling configs.</p>
      </div>

      <ApiRouteList routes={routes} onTestRoute={handleTest} />
    </div>
  );
}
